name: saucectl puppeteer tests

on:
  pull_request:
  push:
    branches:
      - master

env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: saucelabs/saucectl-run-action@v1
        with:
          testing-environment: docker
          concurrency: 10
